export const perguntasWizard = [
  {
    id: 'areaAtual',
    titulo: 'Em qual area voce trabalha hoje?',
    subtitulo: 'Isso ajuda a adaptar a transicao para tecnologia.',
    opcoes: [
      { valor: 'administrativo', rotulo: 'Administrativo ou atendimento' },
      { valor: 'estudante', rotulo: 'Estudante' },
      { valor: 'tecnologia', rotulo: 'Ja trabalho com tecnologia' },
      { valor: 'outra', rotulo: 'Outra area' },
    ],
  },
  {
    id: 'areaDesejada',
    titulo: 'Qual caminho em tecnologia mais combina com voce?',
    subtitulo: 'Escolha o foco principal da sua trilha.',
    opcoes: [
      { valor: 'frontend', rotulo: 'Front-end e interfaces' },
      { valor: 'backend', rotulo: 'Back-end e APIs' },
      { valor: 'dados', rotulo: 'Dados e automacao' },
      { valor: 'devops', rotulo: 'DevOps e cloud' },
      { valor: 'qa', rotulo: 'QA e testes' },
      { valor: 'produto-suporte', rotulo: 'Produto ou suporte tecnico' },
      { valor: 'nao-sei', rotulo: 'Ainda nao sei' },
    ],
  },
  {
    id: 'informatica',
    titulo: 'Como esta sua base de informatica?',
    subtitulo: 'Pode responder sem medo: a plataforma comeca do seu ponto real.',
    opcoes: [
      { valor: 'iniciante', rotulo: 'Tenho dificuldade ate com computador' },
      { valor: 'basico', rotulo: 'Uso o computador para tarefas simples' },
      { valor: 'intermediario', rotulo: 'Uso bem ferramentas e internet' },
      { valor: 'avancado', rotulo: 'Tenho boa autonomia digital' },
    ],
  },
  {
    id: 'programacao',
    titulo: 'Qual e seu nivel em programacao?',
    subtitulo: 'A resposta define se a recomendacao comeca em logica, linguagem ou framework.',
    opcoes: [
      { valor: 'nenhum', rotulo: 'Nunca programei' },
      { valor: 'basico', rotulo: 'Conheco o basico de alguma linguagem' },
      { valor: 'projetos', rotulo: 'Ja fiz pequenos projetos' },
      { valor: 'experiente', rotulo: 'Ja estudo frameworks ou APIs' },
    ],
  },
  {
    id: 'linguagem',
    titulo: 'Qual linguagem voce mais conhece hoje?',
    subtitulo: 'Se nao conhecer nenhuma, escolha a primeira opcao.',
    opcoes: [
      { valor: 'nenhuma', rotulo: 'Nenhuma ainda' },
      { valor: 'javascript', rotulo: 'JavaScript' },
      { valor: 'python', rotulo: 'Python' },
      { valor: 'java', rotulo: 'Java' },
      { valor: 'go', rotulo: 'Go' },
      { valor: 'sql', rotulo: 'SQL' },
    ],
  },
  {
    id: 'tecnologiaInteresse',
    titulo: 'Qual tecnologia voce quer priorizar agora?',
    subtitulo: 'Isso ajuda a indicar cursos mais especificos, como Go basico ou Go para APIs.',
    opcoes: [
      { valor: 'nenhuma', rotulo: 'Ainda nao tenho preferencia' },
      { valor: 'javascript', rotulo: 'JavaScript' },
      { valor: 'react', rotulo: 'React' },
      { valor: 'node', rotulo: 'Node.js' },
      { valor: 'python', rotulo: 'Python' },
      { valor: 'java', rotulo: 'Java' },
      { valor: 'go', rotulo: 'Go' },
      { valor: 'sql', rotulo: 'SQL' },
      { valor: 'git-github', rotulo: 'Git e GitHub' },
      { valor: 'docker-cloud', rotulo: 'Docker e cloud' },
    ],
  },
  {
    id: 'nivelTecnologia',
    titulo: 'Qual e seu nivel nessa tecnologia de interesse?',
    subtitulo: 'A RiseUp usa isso para separar cursos de entrada, pratica e aprofundamento.',
    opcoes: [
      { valor: 'quero-comecar', rotulo: 'Quero comecar do zero' },
      { valor: 'basico', rotulo: 'Sei o basico' },
      { valor: 'projetos', rotulo: 'Ja fiz projetos' },
      { valor: 'avancar', rotulo: 'Quero me aprofundar' },
    ],
  },
  {
    id: 'ingles',
    titulo: 'Como esta seu ingles para tecnologia?',
    subtitulo: 'Ingles tecnico ajuda em documentacao, entrevistas e vagas.',
    opcoes: [
      { valor: 'baixo', rotulo: 'Tenho muita dificuldade' },
      { valor: 'basico', rotulo: 'Leio palavras e frases simples' },
      { valor: 'intermediario', rotulo: 'Consigo ler documentacao com apoio' },
      { valor: 'avancado', rotulo: 'Consigo estudar em ingles' },
    ],
  },
  {
    id: 'agil',
    titulo: 'Voce conhece metodologias ageis?',
    subtitulo: 'Scrum, Kanban e rotina de equipe aparecem muito em vagas junior.',
    opcoes: [
      { valor: 'nao', rotulo: 'Nao conheco' },
      { valor: 'ouvi', rotulo: 'Ja ouvi falar' },
      { valor: 'basico', rotulo: 'Conheco o basico' },
      { valor: 'pratiquei', rotulo: 'Ja pratiquei em projeto' },
    ],
  },
  {
    id: 'tempoSemanal',
    titulo: 'Quanto tempo voce consegue estudar por semana?',
    subtitulo: 'A recomendacao ajusta ritmo e tamanho dos cursos.',
    opcoes: [
      { valor: 'baixo', rotulo: 'Ate 3 horas' },
      { valor: 'medio', rotulo: '4 a 7 horas' },
      { valor: 'alto', rotulo: '8 a 12 horas' },
      { valor: 'intenso', rotulo: 'Mais de 12 horas' },
    ],
  },
  {
    id: 'objetivo',
    titulo: 'Qual e seu objetivo principal agora?',
    subtitulo: 'Vamos equilibrar estudo, pratica e empregabilidade.',
    opcoes: [
      { valor: 'primeira-vaga', rotulo: 'Conseguir a primeira vaga em TI' },
      { valor: 'portfolio', rotulo: 'Montar portfolio com projetos' },
      { valor: 'transicao', rotulo: 'Migrar de area com seguranca' },
      { valor: 'especializar', rotulo: 'Me especializar em uma stack' },
    ],
  },
  {
    id: 'softSkills',
    titulo: 'Como voce se sente em entrevistas e comunicacao?',
    subtitulo: 'A plataforma tambem recomenda trilhas de carreira e desenvolvimento pessoal.',
    opcoes: [
      { valor: 'baixo', rotulo: 'Tenho bastante inseguranca' },
      { valor: 'medio', rotulo: 'Consigo me comunicar, mas quero melhorar' },
      { valor: 'bom', rotulo: 'Tenho boa comunicacao' },
      { valor: 'forte', rotulo: 'Gosto de apresentar e conversar' },
    ],
  },
]
