export const perguntasWizard = [
  {
    id: 'areaAtual',
    titulo: 'Em qual área você trabalha hoje?',
    subtitulo: 'Isso ajuda a adaptar a transição para tecnologia.',
    opcoes: [
      { valor: 'administrativo', rotulo: 'Administrativo ou atendimento' },
      { valor: 'estudante', rotulo: 'Estudante' },
      { valor: 'tecnologia', rotulo: 'Já trabalho com tecnologia' },
      { valor: 'outra', rotulo: 'Outra área' },
    ],
  },
  {
    id: 'areaDesejada',
    titulo: 'Qual caminho em tecnologia mais combina com você?',
    subtitulo: 'Escolha o foco principal da sua trilha.',
    opcoes: [
      { valor: 'frontend', rotulo: 'Front-end e interfaces' },
      { valor: 'backend', rotulo: 'Back-end e APIs' },
      { valor: 'dados', rotulo: 'Dados e automação' },
      { valor: 'devops', rotulo: 'DevOps e cloud' },
      { valor: 'qa', rotulo: 'QA e testes' },
      { valor: 'produto-suporte', rotulo: 'Produto ou suporte técnico' },
      { valor: 'nao-sei', rotulo: 'Ainda não sei' },
    ],
  },
  {
    id: 'informatica',
    titulo: 'Como está sua base de informática?',
    subtitulo: 'Pode responder sem medo: a plataforma começa do seu ponto real.',
    opcoes: [
      { valor: 'iniciante', rotulo: 'Tenho dificuldade até com computador' },
      { valor: 'basico', rotulo: 'Uso o computador para tarefas simples' },
      { valor: 'intermediario', rotulo: 'Uso bem ferramentas e internet' },
      { valor: 'avancado', rotulo: 'Tenho boa autonomia digital' },
    ],
  },
  {
    id: 'programacao',
    titulo: 'Qual é seu nível em programação?',
    subtitulo: 'A resposta define se a recomendação começa em lógica, linguagem ou framework.',
    opcoes: [
      { valor: 'nenhum', rotulo: 'Nunca programei' },
      { valor: 'basico', rotulo: 'Conheço o básico de alguma linguagem' },
      { valor: 'projetos', rotulo: 'Já fiz pequenos projetos' },
      { valor: 'experiente', rotulo: 'Já estudo frameworks ou APIs' },
    ],
  },
  {
    id: 'linguagem',
    titulo: 'Qual linguagem você mais conhece hoje?',
    subtitulo: 'Se não conhecer nenhuma, escolha a primeira opção.',
    opcoes: [
      { valor: 'nenhuma', rotulo: 'Nenhuma ainda' },
      { valor: 'javascript', rotulo: 'JavaScript' },
      { valor: 'python', rotulo: 'Python' },
      { valor: 'java', rotulo: 'Java' },
      { valor: 'go', rotulo: 'Go' },
      { valor: 'php', rotulo: 'PHP' },
      { valor: 'sql', rotulo: 'SQL' },
    ],
  },
  {
    id: 'tecnologiaInteresse',
    titulo: 'Qual tecnologia você quer priorizar agora?',
    subtitulo: 'Isso ajuda a indicar cursos mais específicos, como Go básico ou Go para APIs.',
    opcoes: [
      { valor: 'nenhuma', rotulo: 'Ainda não tenho preferência' },
      { valor: 'javascript', rotulo: 'JavaScript' },
      { valor: 'react', rotulo: 'React' },
      { valor: 'angular', rotulo: 'Angular' },
      { valor: 'node', rotulo: 'Node.js' },
      { valor: 'python', rotulo: 'Python' },
      { valor: 'java', rotulo: 'Java' },
      { valor: 'go', rotulo: 'Go' },
      { valor: 'php', rotulo: 'PHP' },
      { valor: 'sql', rotulo: 'SQL' },
      { valor: 'git-github', rotulo: 'Git e GitHub' },
      { valor: 'docker-cloud', rotulo: 'Docker e cloud' },
    ],
  },
  {
    id: 'nivelTecnologia',
    titulo: 'Qual é seu nível nessa tecnologia de interesse?',
    subtitulo: 'A plataforma usa isso para separar cursos de entrada, prática e aprofundamento.',
    opcoes: [
      { valor: 'quero-comecar', rotulo: 'Quero começar do zero' },
      { valor: 'basico', rotulo: 'Sei o básico' },
      { valor: 'projetos', rotulo: 'Já fiz projetos' },
      { valor: 'avancar', rotulo: 'Quero me aprofundar' },
    ],
  },
  {
    id: 'ingles',
    titulo: 'Como está seu inglês para tecnologia?',
    subtitulo: 'Inglês técnico ajuda em documentação, entrevistas e vagas.',
    opcoes: [
      { valor: 'baixo', rotulo: 'Tenho muita dificuldade' },
      { valor: 'basico', rotulo: 'Leio palavras e frases simples' },
      { valor: 'intermediario', rotulo: 'Consigo ler documentação com apoio' },
      { valor: 'avancado', rotulo: 'Consigo estudar em inglês' },
    ],
  },
  {
    id: 'agil',
    titulo: 'Você conhece metodologias ágeis?',
    subtitulo: 'Scrum, Kanban e rotina de equipe aparecem muito em vagas júnior.',
    opcoes: [
      { valor: 'nao', rotulo: 'Não conheço' },
      { valor: 'ouvi', rotulo: 'Já ouvi falar' },
      { valor: 'basico', rotulo: 'Conheço o básico' },
      { valor: 'pratiquei', rotulo: 'Já pratiquei em projeto' },
    ],
  },
  {
    id: 'tempoSemanal',
    titulo: 'Quanto tempo você consegue estudar por semana?',
    subtitulo: 'A recomendação ajusta ritmo e tamanho dos cursos.',
    opcoes: [
      { valor: 'baixo', rotulo: 'Até 3 horas' },
      { valor: 'medio', rotulo: '4 a 7 horas' },
      { valor: 'alto', rotulo: '8 a 12 horas' },
      { valor: 'intenso', rotulo: 'Mais de 12 horas' },
    ],
  },
  {
    id: 'objetivo',
    titulo: 'Qual é seu objetivo principal agora?',
    subtitulo: 'Vamos equilibrar estudo, prática e empregabilidade.',
    opcoes: [
      { valor: 'primeira-vaga', rotulo: 'Conseguir a primeira vaga em TI' },
      { valor: 'portfolio', rotulo: 'Montar portfólio com projetos' },
      { valor: 'transicao', rotulo: 'Migrar de área com segurança' },
      { valor: 'especializar', rotulo: 'Me especializar em uma stack' },
    ],
  },
  {
    id: 'softSkills',
    titulo: 'Como você se sente em entrevistas e comunicação?',
    subtitulo: 'A plataforma também recomenda trilhas de carreira e desenvolvimento pessoal.',
    opcoes: [
      { valor: 'baixo', rotulo: 'Tenho bastante insegurança' },
      { valor: 'medio', rotulo: 'Consigo me comunicar, mas quero melhorar' },
      { valor: 'bom', rotulo: 'Tenho boa comunicação' },
      { valor: 'forte', rotulo: 'Gosto de apresentar e conversar' },
    ],
  },
];