import { cursos } from './cursos'
import { duracaoDosCursos, minutosParaDuracao } from '../servicos/duracao'

function cursoPorId(id) {
  return cursos.find((curso) => curso.id === id)
}

function cursosPorIds(ids) {
  return ids
    .map((id) => {
      const curso = cursoPorId(id)

      if (!curso && import.meta.env?.DEV) {
        console.warn(`Curso nao encontrado para trilha: ${id}`)
      }

      return curso
    })
    .filter(Boolean)
}

function duracaoDeCursos(ids) {
  return minutosParaDuracao(duracaoDosCursos(cursosPorIds(ids)))
}

function modulosDoCurso(id) {
  const curso = cursoPorId(id)
  if (!curso) return []

  if (Array.isArray(curso.modulos) && curso.modulos.length) {
    return curso.modulos.map((modulo, indice) => ({
      ...modulo,
      id: modulo.id || `${id}-modulo-${indice + 1}`,
      cursoId: id,
      cursoTitulo: curso.titulo,
      descricao: modulo.descricao || curso.destaque || curso.descricao,
      aulas: modulo.aulas || [],
    }))
  }

  return [{
    id: `${id}-jornada`,
    cursoId: id,
    cursoTitulo: curso.titulo,
    titulo: curso.titulo,
    descricao: curso.destaque || curso.descricao,
    aulas: curso.aulas || [],
  }]
}

function modulosDeCursos(ids) {
  return ids.flatMap(modulosDoCurso)
}

function criarTrilhaComCursos({ cursoIds = [], duracao, ...trilha }) {
  const duracaoCalculada = duracaoDeCursos(cursoIds)

  return {
    ...trilha,
    duracao: duracaoCalculada || duracao || '0m',
    cursoIds,
    modulos: modulosDeCursos(cursoIds),
  }
}

export const trilhas = [
  criarTrilhaComCursos({
    id: 'informatica-essencial',
    titulo: 'Informatica Essencial',
    categoria: 'Fundamentos',
    area: 'fundamentos',
    nivel: 'Iniciante',
    tempoSugerido: '2 semanas',
    tecnologias: ['informatica'],
    ordemBase: 1,
    tags: ['informatica', 'iniciante', 'windows', 'fundamentos', 'autonomia-digital'],
    descricao: 'Ganhe autonomia no computador com informatica basica, Windows, arquivos, internet, seguranca e rotina de estudo.',
    destaque: 'Comece pelo basico digital sem pular etapas.',
    cursoIds: ['curso-info-computador', 'curso-info-windows'],
  }),
  criarTrilhaComCursos({
    id: 'logica-algoritmos',
    titulo: 'Logica de Programacao e Algoritmos',
    categoria: 'Programacao',
    area: 'fundamentos',
    nivel: 'Iniciante',
    tempoSugerido: '6 semanas',
    tecnologias: ['logica', 'python', 'estrutura-de-dados'],
    ordemBase: 2,
    tags: ['logica', 'algoritmos', 'iniciante', 'portugol', 'base', 'python', 'estruturas-de-dados'],
    descricao: 'Construa base de raciocinio com logica, exercicios, Python inicial e estruturas de dados simples.',
    destaque: 'Base recomendada antes de escolher framework ou stack.',
    cursoIds: ['curso-logica-zero', 'curso-python-basico', 'curso-logica-typescript', 'curso-estruturas-de-dados-basico'],
  }),
  criarTrilhaComCursos({
    id: 'git-github',
    titulo: 'Git e GitHub para Projetos',
    categoria: 'Ferramentas',
    area: 'fundamentos',
    nivel: 'Iniciante',
    tempoSugerido: '3 semanas',
    tecnologias: ['git-github'],
    ordemBase: 3,
    tags: ['git', 'github', 'portfolio', 'versionamento', 'fundamentos'],
    descricao: 'Aprenda versionamento, GitHub, branches, pull request, colaboracao e uso do GitHub como vitrine profissional.',
    destaque: 'Essencial para portfolio e trabalho em equipe.',
    cursoIds: ['curso-git-github', 'curso-git-github-equipes', 'curso-portfolio-entrevista'],
  }),
  criarTrilhaComCursos({
    id: 'javascript-frontend',
    titulo: 'Front-end com HTML, CSS e JavaScript',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Basico',
    tempoSugerido: '7 semanas',
    tecnologias: ['javascript', 'html', 'css', 'git-github', 'api-rest'],
    ordemBase: 4,
    tags: ['javascript', 'frontend', 'html', 'css', 'dom', 'portfolio', 'api', 'github'],
    descricao: 'Construa uma base completa de Front-end com HTML, CSS, JavaScript, DOM, Git, publicacao e primeiros projetos para portfolio.',
    destaque: 'Trilha base para chegar preparado em React ou Angular.',
    cursoIds: [
      'curso-html-css-js',
      'curso-js-dom',
      'curso-git-github',
      'curso-git-github-equipes',
      'fundamentos-http-api-web',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'frontend-base-portfolio',
    titulo: 'Front-end Base e Portfolio',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Basico',
    tempoSugerido: '7 semanas',
    tecnologias: ['javascript', 'html', 'css', 'git-github', 'carreira'],
    ordemBase: 20,
    tags: ['frontend', 'portfolio', 'primeira-vaga', 'javascript', 'github', 'linkedin'],
    descricao: 'Jornada para criar primeiras telas, praticar DOM, publicar projetos, montar portfolio e preparar LinkedIn para primeira vaga.',
    destaque: 'Caminho pratico para quem quer primeira oportunidade em Front-end.',
    cursoIds: [
      'curso-html-css-js',
      'curso-js-dom',
      'curso-git-github',
      'curso-git-github-equipes',
      'curso-linkedin-sem-experiencia',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'react-frontend',
    titulo: 'React para Front-end',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Intermediario',
    tempoSugerido: '6 semanas',
    tecnologias: ['react', 'javascript', 'api-rest', 'git-github'],
    ordemBase: 5,
    tags: ['react', 'frontend', 'componentes', 'router', 'spa', 'portfolio', 'sass', 'deploy'],
    descricao: 'Evolua da base JavaScript para componentes React, rotas, consumo de API, deploy e portfolio publicado.',
    destaque: 'Proximo passo natural depois de JavaScript e DOM.',
    cursoIds: [
      'curso-html-css-js',
      'curso-js-dom',
      'curso-react-basico',
      'curso-react-dashboard',
      'fundamentos-http-api-web',
      'curso-git-github',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'angular-frontend',
    titulo: 'Angular para Front-end',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Intermediario',
    tempoSugerido: '6 semanas',
    tecnologias: ['angular', 'javascript', 'typescript', 'api-rest', 'git-github'],
    ordemBase: 6,
    tags: ['angular', 'frontend', 'typescript', 'javascript', 'spa', 'testes', 'docker', 'deploy', 'ci-cd', 'portfolio'],
    descricao: 'Prepare a base de JavaScript e TypeScript, construa Angular na pratica, entenda APIs, versionamento, Docker e portfolio.',
    destaque: 'Boa escolha para quem quer front-end estruturado com projetos completos.',
    cursoIds: [
      'curso-html-css-js',
      'curso-logica-typescript',
      'curso-angular-basico',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-git-github',
      'curso-docker-basico',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'node-backend',
    titulo: 'Back-end com Node.js',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Basico',
    tempoSugerido: '8 semanas',
    tecnologias: ['node', 'javascript', 'api-rest', 'sql', 'mongodb'],
    ordemBase: 7,
    tags: ['node', 'backend', 'api', 'javascript', 'express', 'mongodb', 'crud', 'sql', 'seguranca', 'docker'],
    descricao: 'Construa uma jornada Back-end com Git, HTTP, APIs Node, CRUD, SQL, MongoDB, seguranca, Docker e portfolio.',
    destaque: 'Boa ponte para quem vem do JavaScript e quer criar APIs reais.',
    cursoIds: [
      'curso-git-github',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-node-api',
      'curso-node-crud',
      'curso-sql-consultas',
      'curso-mongodb-basico-avancado',
      'seguranca-software-owasp',
      'curso-docker-basico',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'backend-api-base',
    titulo: 'Back-end e APIs Base',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Basico',
    tempoSugerido: '7 semanas',
    tecnologias: ['api', 'api-rest', 'sql', 'node', 'git-github'],
    ordemBase: 21,
    tags: ['backend', 'api', 'http', 'sql', 'node', 'portfolio', 'primeira-vaga'],
    descricao: 'Caminho para quem quer Back-end ou APIs, mas ainda nao definiu stack: logica, Git, HTTP, REST, SQL e primeiro projeto.',
    destaque: 'Base tecnica para escolher Node, Java, PHP ou outra stack depois.',
    cursoIds: [
      'curso-logica-zero',
      'curso-git-github',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-sql-consultas',
      'curso-node-api',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'java-spring',
    titulo: 'Back-end com Java e Spring Boot',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    tempoSugerido: '8 semanas',
    tecnologias: ['java', 'java-spring', 'api-rest', 'sql', 'git-github'],
    ordemBase: 8,
    tags: ['java', 'backend', 'spring', 'api', 'poo', 'jpa', 'security', 'jwt', 'sql', 'testes'],
    descricao: 'Aprenda Java, HTTP, SQL, Spring Boot, JPA, seguranca, testes e Docker em uma sequencia de back-end profissional.',
    destaque: 'Boa evolucao para mirar vagas back-end junior com Java.',
    cursoIds: [
      'curso-java-poo',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-sql-consultas',
      'curso-java-spring-api',
      'curso-spring-boot-api-erudio',
      'curso-git-github',
      'curso-testes-unitarios-junit-mockito',
      'curso-docker-basico',
    ],
  }),
  criarTrilhaComCursos({
    id: 'backend-java-profissional',
    titulo: 'Back-end Java Profissional',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    tempoSugerido: '16 semanas',
    tecnologias: ['java', 'sql', 'git-github', 'docker-cloud'],
    ordemBase: 30,
    tags: [
      'java',
      'spring',
      'backend',
      'api',
      'api-rest',
      'sql',
      'junit',
      'mockito',
      'arquitetura',
      'mensageria',
      'docker',
      'devops',
      'seguranca',
      'portfolio',
    ],
    descricao:
      'Uma jornada completa para sair da base e construir repertorio profissional em Java, APIs, banco de dados, testes, arquitetura, mensageria, DevOps e seguranca.',
    destaque: 'Caminho robusto para quem quer evoluir em back-end Java com projetos reais.',
    cursoIds: [
      'curso-logica-zero',
      'curso-git-github',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-sql-consultas',
      'curso-java-poo',
      'curso-java-spring-api',
      'curso-spring-boot-api-erudio',
      'curso-testes-unitarios-junit-mockito',
      'curso-design-patterns-poo',
      'curso-arquitetura-limpa-java',
      'curso-mensageria-microservices',
      'curso-docker-basico',
      'devops-cloud-ci-cd',
      'seguranca-software-owasp',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'php-backend',
    titulo: 'Back-end com PHP',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Basico',
    tempoSugerido: '6 semanas',
    tecnologias: ['php', 'sql', 'api-rest', 'git-github'],
    ordemBase: 9,
    tags: ['php', 'backend', 'web', 'html', 'formularios', 'servidor', 'banco-de-dados', 'portfolio', 'seguranca'],
    descricao: 'Aprenda PHP para web com formularios, SQL, HTTP/API, autenticacao, seguranca e publicacao de projetos.',
    destaque: 'Caminho pratico para quem quer back-end web com PHP.',
    cursoIds: [
      'curso-php-iniciante',
      'curso-sql-consultas',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-jwt-php',
      'seguranca-software-owasp',
      'curso-git-github',
    ],
  }),
  criarTrilhaComCursos({
    id: 'backend-php-web-profissional',
    titulo: 'Back-end PHP Web Profissional',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    tempoSugerido: '10 semanas',
    tecnologias: ['php', 'sql', 'api-rest', 'seguranca'],
    ordemBase: 35,
    tags: ['php', 'backend', 'api', 'sql', 'jwt', 'seguranca', 'portfolio'],
    descricao: 'Jornada profissional para evoluir em PHP web com banco, APIs, autenticacao JWT, seguranca, Git e portfolio.',
    destaque: 'Para quem quer transformar PHP em projeto profissional.',
    cursoIds: [
      'curso-php-iniciante',
      'curso-sql-consultas',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-jwt-php',
      'seguranca-software-owasp',
      'curso-git-github',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'go-backend',
    titulo: 'Back-end com Go',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    tempoSugerido: '5 semanas',
    tecnologias: ['go', 'api-rest', 'git-github'],
    ordemBase: 10,
    tags: ['go', 'golang', 'backend', 'api', 'concorrencia'],
    descricao: 'Aprenda Go com fundamentos, APIs, HTTP e Git para construir servicos simples e publicaveis.',
    destaque: 'Escolha direta para quem tem interesse explicito em Go.',
    cursoIds: ['curso-go-basico', 'fundamentos-http-api-web', 'curso-go-api', 'curso-git-github'],
  }),
  criarTrilhaComCursos({
    id: 'python-dados',
    titulo: 'Python para Dados e Automacao',
    categoria: 'Dados',
    area: 'dados',
    nivel: 'Intermediario',
    tempoSugerido: '8 semanas',
    tecnologias: ['python', 'sql', 'mongodb', 'git-github'],
    ordemBase: 12,
    tags: ['python', 'dados', 'automacao', 'pandas', 'numpy', 'visualizacao', 'webscraping', 'portfolio'],
    descricao: 'Jornada de Dados com Python basico, SQL, analise, Pandas, Numpy, visualizacao, automacao, MongoDB, Git e portfolio.',
    destaque: 'Boa opcao para evoluir de Python basico para analise de dados real.',
    cursoIds: [
      'curso-python-basico',
      'curso-sql-consultas',
      'curso-python-dados',
      'curso-mongodb-basico-avancado',
      'curso-git-github',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'dados-base-primeira-vaga',
    titulo: 'Dados Base para Primeira Vaga',
    categoria: 'Dados',
    area: 'dados',
    nivel: 'Basico',
    tempoSugerido: '7 semanas',
    tecnologias: ['python', 'sql', 'git-github', 'carreira'],
    ordemBase: 22,
    tags: ['dados', 'python', 'sql', 'primeira-vaga', 'portfolio', 'linkedin'],
    descricao: 'Caminho inicial para Dados com logica, Python, SQL, Git, LinkedIn e portfolio para apresentar sua evolucao.',
    destaque: 'Base de Dados para quem esta mirando primeira oportunidade.',
    cursoIds: [
      'curso-logica-zero',
      'curso-python-basico',
      'curso-sql-consultas',
      'curso-git-github',
      'curso-linkedin-sem-experiencia',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'dados-python-sql-profissional',
    titulo: 'Dados com Python e SQL Profissional',
    categoria: 'Dados',
    area: 'dados',
    nivel: 'Intermediario',
    tempoSugerido: '10 semanas',
    tecnologias: ['python', 'sql', 'mongodb', 'git-github'],
    ordemBase: 36,
    tags: ['dados', 'python', 'sql', 'pandas', 'automacao', 'mongodb', 'portfolio'],
    descricao: 'Aprofunde Dados com Python, SQL, analise, automacao, MongoDB, Git e portfolio para projetos mais fortes.',
    destaque: 'Para quem ja tem base e quer avancar em Dados com projetos.',
    cursoIds: [
      'curso-python-basico',
      'curso-sql-consultas',
      'curso-python-dados',
      'curso-mongodb-basico-avancado',
      'curso-git-github',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'sql-banco-dados',
    titulo: 'SQL e Banco de Dados',
    categoria: 'Dados',
    area: 'dados',
    nivel: 'Basico',
    tempoSugerido: '4 semanas',
    tecnologias: ['sql'],
    ordemBase: 11,
    tags: ['sql', 'banco-de-dados', 'dados', 'backend', 'consultas'],
    descricao: 'Aprenda introducao a banco, criacao de tabelas, SELECT, JOIN, chaves, relacionamento e consultas com MySQL.',
    destaque: 'Complemento forte para dados, back-end e suporte tecnico.',
    cursoIds: ['curso-sql-consultas'],
  }),
  criarTrilhaComCursos({
    id: 'devops-base-docker',
    titulo: 'DevOps Base com Git, Linux e Docker',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Basico',
    tempoSugerido: '6 semanas',
    tecnologias: ['git-github', 'linux', 'docker-cloud', 'seguranca'],
    ordemBase: 23,
    tags: ['devops', 'docker', 'linux', 'git', 'cloud', 'seguranca', 'iniciante'],
    descricao: 'Base de DevOps para iniciantes com Git, Linux, Docker, nocao de cloud, seguranca e HTTP/API.',
    destaque: 'Primeiro caminho para entender deploy e infraestrutura.',
    cursoIds: [
      'curso-git-github',
      'linux-para-iniciantes',
      'curso-docker-basico',
      'curso-seguranca-informacao-pratica',
      'fundamentos-http-api-web',
    ],
  }),
  criarTrilhaComCursos({
    id: 'devops-docker-cloud',
    titulo: 'DevOps Inicial com Docker e Cloud',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Basico',
    tempoSugerido: '10 semanas',
    tecnologias: ['docker-cloud', 'linux', 'git-github', 'seguranca'],
    ordemBase: 13,
    tags: ['devops', 'docker', 'docker-compose', 'linux', 'aws', 'cloud', 'ci-cd', 'deploy', 'infra', 'seguranca', 'api'],
    descricao:
      'Jornada para publicar e manter aplicacoes com Git, Linux, Docker, Docker Compose, AWS, CI/CD, seguranca e nocao de HTTP/API.',
    destaque: 'Para quem quer publicar projetos e entender ambientes de producao.',
    cursoIds: [
      'curso-git-github',
      'linux-para-iniciantes',
      'curso-docker-basico',
      'curso-cloud-deploy',
      'curso-aws-cloud-practitioner',
      'devops-cloud-ci-cd',
      'curso-seguranca-informacao-pratica',
      'seguranca-software-owasp',
      'fundamentos-http-api-web',
    ],
  }),
  criarTrilhaComCursos({
    id: 'devops-cloud-profissional',
    titulo: 'DevOps e Cloud Profissional',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Intermediario',
    tempoSugerido: '14 semanas',
    tecnologias: ['docker-cloud', 'linux', 'git-github', 'seguranca'],
    ordemBase: 34,
    tags: ['devops', 'docker', 'docker-compose', 'cloud', 'aws', 'linux', 'ci-cd', 'deploy', 'seguranca', 'portfolio'],
    descricao:
      'Jornada profissional para operar projetos com Git, Linux, Docker, cloud, AWS, CI/CD, deploy, seguranca e fundamentos de HTTP/API.',
    destaque: 'Caminho robusto para quem quer evoluir em infraestrutura, containers e cloud.',
    cursoIds: [
      'curso-git-github',
      'linux-para-iniciantes',
      'curso-docker-basico',
      'curso-cloud-deploy',
      'curso-aws-cloud-practitioner',
      'devops-cloud-ci-cd',
      'curso-seguranca-informacao-pratica',
      'seguranca-software-owasp',
      'fundamentos-http-api-web',
    ],
  }),
  criarTrilhaComCursos({
    id: 'linux-fundamentos',
    titulo: 'Linux para DevOps',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Iniciante',
    tempoSugerido: '3 semanas',
    tecnologias: ['linux', 'git-github'],
    ordemBase: 17,
    tags: ['linux', 'terminal', 'devops', 'infra', 'servidores'],
    descricao: 'Base de Linux, terminal e Git para trabalhar melhor com servidores, deploy e ambientes de desenvolvimento.',
    destaque: 'Complemento direto para quem quer atuar com DevOps e infraestrutura.',
    cursoIds: ['linux-para-iniciantes', 'curso-git-github'],
  }),
  criarTrilhaComCursos({
    id: 'seguranca-informacao',
    titulo: 'Seguranca para Projetos Web',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Basico',
    tempoSugerido: '4 semanas',
    tecnologias: ['seguranca', 'api-rest'],
    ordemBase: 18,
    tags: ['seguranca', 'owasp', 'boas-praticas', 'api-rest', 'web', 'devops'],
    descricao: 'Fundamentos de seguranca da informacao e boas praticas OWASP para proteger sistemas web e APIs.',
    destaque: 'Ajuda a publicar e manter aplicacoes com mais cuidado e criterio.',
    cursoIds: ['curso-seguranca-informacao-pratica', 'seguranca-software-owasp'],
  }),
  criarTrilhaComCursos({
    id: 'api-http-rest',
    titulo: 'HTTP e APIs REST',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Basico',
    tempoSugerido: '3 semanas',
    tecnologias: ['api', 'api-rest'],
    ordemBase: 19,
    tags: ['http', 'api', 'api-rest', 'backend', 'qa', 'devops'],
    descricao: 'Entenda HTTP, REST, status codes, parametros, metodos e boas praticas antes de integrar, testar ou publicar APIs.',
    destaque: 'Complemento util para back-end, QA e DevOps.',
    cursoIds: ['fundamentos-http-api-web', 'curso-rest-api-fundamentos'],
  }),
  criarTrilhaComCursos({
    id: 'qa-testes',
    titulo: 'QA e Testes para Iniciantes',
    categoria: 'QA',
    area: 'qa',
    nivel: 'Iniciante',
    tempoSugerido: '5 semanas',
    tecnologias: ['qa', 'git-github', 'api-rest'],
    ordemBase: 14,
    tags: ['qa', 'testes', 'qualidade', 'bugs', 'produto', 'automacao', 'api', 'mobile', 'appium', 'portfolio'],
    descricao: 'Aprenda fundamentos de QA, cenarios de teste, bugs, Git, HTTP/API, testes de API e primeiros passos de carreira.',
    destaque: 'Uma entrada pratica para quem gosta de detalhe, produto e qualidade.',
    cursoIds: [
      'curso-qa-manual',
      'curso-git-github',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'testes-api-rest-completo',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'qa-base-primeira-vaga',
    titulo: 'QA Base para Primeira Vaga',
    categoria: 'QA',
    area: 'qa',
    nivel: 'Basico',
    tempoSugerido: '6 semanas',
    tecnologias: ['qa', 'git-github', 'api-rest', 'carreira'],
    ordemBase: 24,
    tags: ['qa', 'primeira-vaga', 'testes', 'api', 'portfolio', 'linkedin'],
    descricao: 'Caminho inicial para QA com logica, Git, fundamentos de testes, HTTP/API, LinkedIn e portfolio.',
    destaque: 'Base de QA para quem quer entrar no mercado.',
    cursoIds: [
      'curso-logica-zero',
      'curso-git-github',
      'curso-qa-manual',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-linkedin-sem-experiencia',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'backend-node-api-profissional',
    titulo: 'Back-end Node API Profissional',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    tempoSugerido: '12 semanas',
    tecnologias: ['node', 'javascript', 'api-rest', 'sql'],
    ordemBase: 31,
    tags: ['node', 'javascript', 'backend', 'api', 'api-rest', 'sql', 'mongodb', 'seguranca', 'docker', 'portfolio'],
    descricao: 'Jornada para construir APIs profissionais com Node, banco de dados, seguranca, Docker e portfolio.',
    destaque: 'Caminho robusto para quem conhece JavaScript e quer evoluir em APIs.',
    cursoIds: [
      'curso-git-github',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-node-api',
      'curso-node-crud',
      'curso-sql-consultas',
      'curso-mongodb-basico-avancado',
      'seguranca-software-owasp',
      'curso-docker-basico',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'qa-automacao-profissional',
    titulo: 'QA Automacao Profissional',
    categoria: 'QA',
    area: 'qa',
    nivel: 'Intermediario',
    tempoSugerido: '10 semanas',
    tecnologias: ['qa', 'api-rest', 'git-github', 'docker-cloud'],
    ordemBase: 32,
    tags: ['qa', 'testes', 'automacao', 'cypress', 'api-rest', 'ci-cd', 'docker', 'seguranca'],
    descricao: 'Jornada de QA com testes manuais, automacao, testes de API, Git, CI/CD, Docker e seguranca basica.',
    destaque: 'Para evoluir de fundamentos de QA para automacao e rotina profissional.',
    cursoIds: [
      'curso-git-github',
      'curso-qa-manual',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'testes-api-rest-completo',
      'curso-cypress-automacao-testes',
      'devops-cloud-ci-cd',
      'curso-docker-basico',
      'seguranca-software-owasp',
    ],
  }),
  criarTrilhaComCursos({
    id: 'frontend-angular-profissional',
    titulo: 'Front-end Angular Profissional',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Intermediario',
    tempoSugerido: '10 semanas',
    tecnologias: ['angular', 'typescript', 'javascript', 'design-system'],
    ordemBase: 33,
    tags: ['angular', 'typescript', 'javascript', 'frontend', 'design-system', 'testes', 'deploy', 'portfolio'],
    descricao: 'Jornada de front-end com JavaScript, TypeScript, Angular, design system, testes, deploy e portfolio.',
    destaque: 'Caminho maior para quem quer se aprofundar em Angular com projetos completos.',
    cursoIds: [
      'curso-html-css-js',
      'curso-logica-typescript',
      'curso-angular-basico',
      'curso-design-system-figma',
      'curso-git-github',
      'curso-docker-basico',
      'devops-cloud-ci-cd',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'suporte-tecnico-inicial',
    titulo: 'Suporte Tecnico Inicial',
    categoria: 'Fundamentos',
    area: 'produto-suporte',
    nivel: 'Iniciante',
    tempoSugerido: '5 semanas',
    tecnologias: ['informatica', 'linux', 'seguranca', 'carreira'],
    ordemBase: 25,
    tags: ['suporte', 'informatica', 'windows', 'linux', 'seguranca', 'atendimento'],
    descricao: 'Base para suporte tecnico com informatica, Windows, Linux inicial, seguranca e comunicacao com pessoas.',
    destaque: 'Caminho para quem quer entrar por suporte ou atendimento tecnico.',
    cursoIds: [
      'curso-info-computador',
      'curso-info-windows',
      'linux-para-iniciantes',
      'curso-seguranca-informacao-pratica',
      'curso-oratoria-kultivi',
    ],
  }),
  criarTrilhaComCursos({
    id: 'produto-suporte-carreira',
    titulo: 'Produto, Suporte e Carreira em Tecnologia',
    categoria: 'Carreira',
    area: 'produto-suporte',
    nivel: 'Basico',
    tempoSugerido: '6 semanas',
    tecnologias: ['informatica', 'qa', 'git-github', 'carreira', 'ingles'],
    ordemBase: 26,
    tags: ['produto', 'suporte', 'qa', 'comunicacao', 'carreira', 'ingles'],
    descricao: 'Jornada para quem quer atuar perto de pessoas, produto ou suporte: informatica, QA basico, Git, comunicacao, carreira e ingles.',
    destaque: 'Boa ponte para entrar em tecnologia sem comecar direto por codigo pesado.',
    cursoIds: [
      'curso-info-computador',
      'curso-qa-manual',
      'curso-git-github',
      'curso-oratoria-kultivi',
      'curso-ingles-docs',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'ingles-tech',
    titulo: 'Ingles para Tecnologia',
    categoria: 'Carreira',
    area: 'carreira',
    nivel: 'Iniciante',
    tempoSugerido: '3 semanas',
    tecnologias: ['ingles'],
    ordemBase: 15,
    tags: ['ingles', 'programacao', 'entrevista', 'carreira', 'internacional'],
    descricao: 'Aprenda vocabulario tecnico, pronuncia, cargos em tecnologia e perguntas comuns em entrevistas em ingles.',
    destaque: 'Complemento importante para aumentar empregabilidade.',
    cursoIds: ['curso-ingles-docs'],
  }),
  criarTrilhaComCursos({
    id: 'carreira-comunicacao',
    titulo: 'Carreira, Comunicacao e Portfolio',
    categoria: 'Soft skills',
    area: 'carreira',
    nivel: 'Todos',
    tempoSugerido: '3 semanas',
    tecnologias: ['carreira'],
    ordemBase: 16,
    tags: ['soft-skills', 'entrevista', 'portfolio', 'retorica', 'comunicacao', 'linkedin'],
    descricao: 'Desenvolva comunicacao, LinkedIn, curriculo, portfolio, entrevista, storytelling de projetos e postura profissional.',
    destaque: 'Ajuda a transformar estudo em oportunidade.',
    cursoIds: [
      'curso-oratoria-kultivi',
      'curso-linkedin-sem-experiencia',
      'curso-empregabilidade-linkedin-ia',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'primeira-vaga-portfolio',
    titulo: 'Primeira Vaga e Portfolio',
    categoria: 'Carreira',
    area: 'carreira',
    nivel: 'Todos',
    tempoSugerido: '3 semanas',
    tecnologias: ['carreira', 'git-github'],
    ordemBase: 27,
    tags: ['primeira-vaga', 'portfolio', 'github', 'linkedin', 'entrevista', 'comunicacao'],
    descricao: 'Monte presenca profissional com GitHub, LinkedIn, portfolio, curriculo, entrevistas e comunicacao.',
    destaque: 'Complemento de carreira para mostrar melhor seus projetos.',
    cursoIds: [
      'curso-git-github',
      'curso-linkedin-sem-experiencia',
      'curso-empregabilidade-linkedin-ia',
      'curso-portfolio-entrevista',
    ],
  }),
]
