export const vagas = [
  {
    id: 'vaga-1',
    empresaId: 'empresa-1',
    titulo: 'Desenvolvedor Front-end Junior',
    nivel: 'Junior',
    tipo: 'CLT',
    modalidade: 'Hibrido',
    localizacao: 'Recife, PE',
    salario: 'R$ 2.800 - R$ 3.600',
    status: 'ativa',
    publicadaEm: '2026-04-12',
    candidatos: 8,
    tags: ['javascript', 'frontend', 'html', 'css'],
    descricao:
      'Atuar na construcao de interfaces React, manutencao de componentes e melhoria da experiencia do usuario.',
    requisitos: ['HTML e CSS', 'JavaScript basico', 'Git', 'Boa comunicacao'],
    atividades: ['Criar telas responsivas', 'Consumir APIs', 'Participar de rituais ageis'],
  },
  {
    id: 'vaga-2',
    empresaId: 'empresa-1',
    titulo: 'Estagio em Suporte e Dados',
    nivel: 'Estagio',
    tipo: 'Estagio',
    modalidade: 'Presencial',
    localizacao: 'Recife, PE',
    salario: 'R$ 1.100',
    status: 'ativa',
    publicadaEm: '2026-04-20',
    candidatos: 14,
    tags: ['informatica', 'python', 'dados', 'excel'],
    descricao:
      'Apoiar usuarios internos, organizar planilhas e criar pequenas automacoes para a equipe.',
    requisitos: ['Informatica basica', 'Excel ou Sheets', 'Curiosidade por Python'],
    atividades: ['Atendimento inicial', 'Organizacao de dados', 'Documentacao de processos'],
  },
  {
    id: 'vaga-3',
    empresaId: 'empresa-2',
    titulo: 'Back-end Java Junior',
    nivel: 'Junior',
    tipo: 'PJ',
    modalidade: 'Remoto',
    localizacao: 'Brasil',
    salario: 'R$ 3.500 - R$ 4.500',
    status: 'ativa',
    publicadaEm: '2026-04-18',
    candidatos: 5,
    tags: ['java', 'backend', 'spring', 'api'],
    descricao:
      'Criar e manter endpoints REST em projetos de produtos digitais com acompanhamento de pessoas seniors.',
    requisitos: ['Java basico', 'POO', 'Noções de APIs', 'Git'],
    atividades: ['Implementar endpoints', 'Corrigir bugs', 'Escrever documentacao simples'],
  },
  {
    id: 'vaga-4',
    empresaId: 'empresa-2',
    titulo: 'Assistente de Produto Digital',
    nivel: 'Junior',
    tipo: 'CLT',
    modalidade: 'Remoto',
    localizacao: 'Brasil',
    salario: 'R$ 2.400 - R$ 3.000',
    status: 'encerrada',
    publicadaEm: '2026-03-29',
    candidatos: 21,
    tags: ['agil', 'comunicacao', 'portfolio', 'produto'],
    descricao:
      'Apoiar organizacao de backlog, testes de interface e comunicacao entre time tecnico e negocio.',
    requisitos: ['Comunicacao', 'Organizacao', 'Noções de metodologias ageis'],
    atividades: ['Acompanhar tarefas', 'Testar funcionalidades', 'Registrar feedbacks'],
  },
    {
    id: 'vaga-5',
    empresaId: 'empresa-2',
    titulo: 'Assistente de Produto Digitallll',
    nivel: 'Junior',
    tipo: 'CLT',
    modalidade: 'Remoto',
    localizacao: 'Brasil',
    salario: 'R$ 2.400 - R$ 3.000',
    status: 'encerrada',
    publicadaEm: '2026-03-29',
    candidatos: 21,
    tags: ['agil', 'comunicacao', 'portfolio', 'produto'],
    descricao:
      'Apoiar organizacao de backlog, testes de interface e comunicacao entre time tecnico e negocio.',
    requisitos: ['Comunicacao', 'Organizacao', 'Noções de metodologias ageis'],
    atividades: ['Acompanhar tarefas', 'Testar funcionalidades', 'Registrar feedbacks'],
  },
]

export const candidatosMock = [
  {
    id: 'cand-1',
    nome: 'Lucas Andrade',
    status: 'Em andamento',
    cargo: 'Aluno em transicao para TI',
    cursos: ['Introducao a Informatica', 'Logica de Programacao e Algoritmos'],
    tecnologias: ['Logica', 'JavaScript', 'HTML', 'CSS'],
    aderencia: 82,
  },
  {
    id: 'cand-2',
    nome: 'Ana Beatriz Lima',
    status: 'Visto',
    cargo: 'Estudante de ADS',
    cursos: ['JavaScript para Front-end', 'Comunicacao, Entrevistas e Portfolio'],
    tecnologias: ['React', 'JavaScript', 'Git'],
    aderencia: 76,
  },
  {
    id: 'cand-3',
    nome: 'Rafael Souza',
    status: 'Reprovado',
    cargo: 'Tecnico de suporte',
    cursos: ['Python para Automacao e Dados'],
    tecnologias: ['Python', 'Excel', 'Suporte'],
    aderencia: 64,
  },
]
