export const vagas = [
  {
    id: 'vaga-1',
    empresaId: 'empresa-1',
    titulo: 'Desenvolvedor Front-end Júnior',
    nivel: 'Júnior',
    tipo: 'CLT',
    modalidade: 'Híbrido',
    localizacao: 'Recife, PE',
    salario: 'R$ 2.800 - R$ 3.600',
    status: 'ativa',
    publicadaEm: '2026-05-26',
    candidatos: 1,
    tags: ['react', 'typescript', 'frontend', 'fluent-ui', 'azure', 'acessibilidade'],
    descricao:
      'No time de Front-end da Avanade, seu desafio será transformar designs complexos em interfaces fluidas, acessíveis e performáticas dentro do ecossistema Microsoft.',
    requisitos: [
      'HTML5, CSS3, SASS ou Styled Components e JavaScript moderno',
      'Conhecimento em TypeScript para projetos de escala',
      'Noções sólidas de React e gerenciamento de estado',
      'Git/GitHub e familiaridade com ambientes de nuvem',
      'Boa comunicação para atuar com times multidisciplinares',
    ],
    atividades: [
      'Criar interfaces responsivas com React e Fluent UI',
      'Integrar APIs RESTful e fluxos de dados com Azure Functions',
      'Participar de code reviews e apoiar boas práticas de acessibilidade',
      'Atuar em squads globais usando metodologias ágeis e Azure DevOps',
    ],
  },
  {
    id: 'vaga-6',
    empresaId: 'empresa-1',
    titulo: 'Analista de Suporte Técnico Júnior',
    nivel: 'Júnior',
    tipo: 'CLT',
    modalidade: 'Presencial',
    localizacao: 'Recife, PE',
    salario: 'R$ 2.200 - R$ 2.900',
    status: 'ativa',
    publicadaEm: '2026-05-26',
    candidatos: 1,
    tags: ['suporte', 'microsoft-365', 'azure', 'redes', 'itil'],
    descricao:
      'Apoiar usuários internos e equipes de projeto em rotinas de suporte, ambientes Microsoft 365, chamados técnicos e documentação de soluções.',
    requisitos: [
      'Informática intermediária e boa comunicação com usuários',
      'Noções de Windows, redes e Microsoft 365',
      'Organização para registrar chamados e documentar soluções',
      'Interesse por Azure Fundamentals e boas práticas de atendimento',
      'Vontade de aprender com times técnicos em projetos reais',
    ],
    atividades: [
      'Atender chamados de primeiro nível e orientar usuários',
      'Apoiar configuração de acessos, estações e ferramentas Microsoft',
      'Documentar problemas recorrentes e soluções aplicadas',
      'Acompanhar a equipe em rotinas de suporte e melhoria contínua',
    ],
  },
  {
    id: 'vaga-7',
    empresaId: 'empresa-1',
    titulo: 'Desenvolvedor Back-end .NET Júnior',
    nivel: 'Júnior',
    tipo: 'CLT',
    modalidade: 'Remoto',
    localizacao: 'Brasil',
    salario: 'R$ 3.000 - R$ 4.200',
    status: 'encerrada',
    publicadaEm: '2026-04-02',
    candidatos: 0,
    tags: ['dotnet', 'csharp', 'azure', 'api-rest', 'sql'],
    descricao:
      'Vaga antiga para atuar em APIs e integrações no ecossistema Microsoft. Ela permanece no gerenciamento, mas não entra nas vagas recentes do painel.',
    requisitos: [
      'Noções de C#, .NET e APIs REST',
      'Conhecimento básico de SQL',
      'Interesse por Azure e boas práticas de versionamento',
    ],
    atividades: [
      'Apoiar a manutenção de APIs internas',
      'Documentar integrações e corrigir pequenos bugs',
      'Participar de rituais ágeis com o time de engenharia',
    ],
  },
  {
    id: 'vaga-microsoft-cloud-architect',
    empresaId: 'empresa-microsoft',
    titulo: 'Cloud Solutions Architect (Azure)',
    nivel: 'Senior',
    tipo: 'CLT',
    modalidade: 'Remoto',
    localizacao: 'Brasil',
    salario: 'R$ 18.000 - R$ 25.000',
    status: 'ativa',
    publicadaEm: '2026-05-30',
    candidatos: 0,
    tags: ['azure', 'cloud', 'arquitetura', 'devops', 'terraform'],
    descricao:
      'Desenhar arquiteturas escalaveis na nuvem Azure para grandes clientes enterprise, focando em seguranca e performance.',
    requisitos: [
      'Experiencia solida com Azure',
      'Conhecimento em Infrastructure as Code (IaC)',
      'Ingles fluente para reunioes globais',
    ],
    atividades: [
      'Definir arquiteturas cloud para clientes enterprise',
      'Apoiar decisoes de seguranca, performance e escalabilidade',
      'Conduzir discussoes tecnicas com squads locais e globais',
    ],
  },
  {
    id: 'vaga-microsoft-fullstack-dotnet-react',
    empresaId: 'empresa-microsoft',
    titulo: 'Desenvolvedor Full-Stack (.NET & React)',
    nivel: 'Pleno',
    tipo: 'CLT',
    modalidade: 'Hibrido',
    localizacao: 'Sao Paulo, SP',
    salario: 'R$ 9.500 - R$ 13.000',
    status: 'ativa',
    publicadaEm: '2026-05-29',
    candidatos: 0,
    tags: ['dotnet', 'csharp', 'react', 'typescript', 'sql-server'],
    descricao:
      'Atuar no desenvolvimento de ferramentas internas que utilizam o ecossistema Office 365 e integracoes com bancos de dados complexos.',
    requisitos: [
      'Dominio de C#',
      'Experiencia com React.js moderno',
      'Familiaridade com Azure DevOps',
    ],
    atividades: [
      'Desenvolver interfaces e APIs internas',
      'Integrar solucoes com Microsoft 365 e SQL Server',
      'Participar de code reviews e melhorias de arquitetura',
    ],
  },
  {
    id: 'vaga-microsoft-estagio-dados',
    empresaId: 'empresa-microsoft',
    titulo: 'Estagiario em Engenharia de Dados',
    nivel: 'Estagio',
    tipo: 'Estagio',
    modalidade: 'Hibrido',
    localizacao: 'Sao Paulo, SP',
    salario: 'R$ 2.400 - R$ 3.000',
    status: 'ativa',
    publicadaEm: '2026-05-28',
    candidatos: 0,
    tags: ['python', 'sql', 'power-bi', 'dados', 'azure-data-factory'],
    descricao:
      'Apoiar o time de dados na construcao de dashboards e tratamento de pipelines simples para analise de mercado.',
    requisitos: [
      'Cursando tecnologia ou engenharia',
      'Nocoes basicas de SQL e Python',
      'Curiosidade por IA',
    ],
    atividades: [
      'Apoiar a criacao de dashboards em Power BI',
      'Tratar bases de dados para analises internas',
      'Aprender boas praticas de pipelines em Azure Data Factory',
    ],
  },
  {
    id: 'vaga-apple-ios-swift',
    empresaId: 'empresa-apple',
    titulo: 'Desenvolvedor iOS (Swift)',
    nivel: 'Pleno',
    tipo: 'CLT',
    modalidade: 'Hibrido',
    localizacao: 'Jundiai ou Sao Paulo, SP',
    salario: 'R$ 11.000 - R$ 16.000',
    status: 'ativa',
    publicadaEm: '2026-05-27',
    candidatos: 0,
    tags: ['swift', 'swiftui', 'ios', 'mobile', 'clean-architecture'],
    descricao:
      'Criar experiencias incriveis para o ecossistema iOS, focando em animacoes fluidas, performance e seguranca total dos dados.',
    requisitos: [
      'Dominio de Swift',
      'Experiencia com SwiftUI',
      'Conhecimento profundo das diretrizes de design da Apple (HIG)',
    ],
    atividades: [
      'Construir telas nativas com SwiftUI',
      'Otimizar performance, acessibilidade e seguranca',
      'Trabalhar junto a design e produto em novas experiencias mobile',
    ],
  },
  {
    id: 'vaga-apple-designer-produto',
    empresaId: 'empresa-apple',
    titulo: 'Designer de Produto (UX/UI)',
    nivel: 'Senior',
    tipo: 'CLT',
    modalidade: 'Presencial',
    localizacao: 'Sao Paulo, SP',
    salario: 'R$ 13.500 - R$ 19.000',
    status: 'ativa',
    publicadaEm: '2026-05-26',
    candidatos: 0,
    tags: ['figma', 'ux', 'ui', 'design', 'prototipagem', 'acessibilidade'],
    descricao:
      'Liderar o design de novas funcionalidades para aplicativos nativos, garantindo simplicidade, consistencia e alto cuidado visual.',
    requisitos: [
      'Portfolio de alto nivel',
      'Experiencia com acessibilidade digital',
      'Visao critica de usabilidade',
    ],
    atividades: [
      'Criar fluxos, prototipos e especificacoes de produto',
      'Conduzir decisoes de UX com base em clareza e simplicidade',
      'Colaborar com engenharia em detalhes de interacao e acessibilidade',
    ],
  },
]

export const candidatosMock = [
  {
    id: 'cand-1',
    vagaId: 'vaga-1',
    nome: 'Lucas Andrade',
    status: 'Em andamento',
    cargo: 'Aluno em transição para TI',
    localizacao: 'Recife, PE',
    bio: 'Estudante focado em front-end, acessibilidade e construção de interfaces com React.',
    cursos: ['Front-end com HTML, CSS e JavaScript', 'Git e GitHub para Projetos'],
    tecnologias: ['React', 'JavaScript', 'HTML', 'CSS'],
  },
  {
    id: 'cand-2',
    vagaId: 'vaga-6',
    nome: 'Rafael Souza',
    status: 'Em andamento',
    cargo: 'Técnico de suporte',
    localizacao: 'Recife, PE',
    bio: 'Experiência com atendimento de usuários, hardware, redes e documentação técnica.',
    cursos: ['Informática Essencial', 'Git e GitHub para Projetos'],
    tecnologias: ['Suporte', 'Redes', 'Windows', 'Microsoft 365'],
  },
]
